package ch.hsr.greatnamebackend.common.authentication;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;

@Data
public class GoogleIdentityToken {

    @JsonProperty("access_token")
    private String accessToken;

/*    @JsonProperty("token_type")
    private String tokenType;

    @JsonProperty("refresh_token")
    private String refreshToken;

    @JsonProperty("expires_in")
    private int expiresIn;

    private String scope;

    private String jti;*/

    /*
    * client_id,   which you obtain from the API Console Credentials page .
response_type,   which in a basic authorization code flow request should be code. (Read more at response_type.)
scope,   which in a basic request should be openid email. (Read more at scope.)
redirect_uri    should be the HTTP endpoint on your server that will receive the response from Google. The value must exactly match one of the authorized redirect URIs for the OAuth 2.0 client, which you configured in the API Console Credentials page. If this value doesn't match an authorized URI, the request will fail with a redirect_uri_mismatch error.
state    should include the value of the anti-forgery unique session token, as well as any other information needed to recover the context when the user returns to your application, e.g., the starting URL. (Read more at state.)
nonce    is a random value generated by your app that enables replay protection when present.
login_hint    can be the user's email address or the sub string, which is equivalent to the user's Google ID. If you do not provide a login_hint and the user is currently logged in, the consent screen includes a request for approval to release the user's email address to your app. (Read more at login_hint.)
*/
}
